version: "3.8"

services:
  db:
    image: postgres:16
    container_name: falist_db
    restart: always
    environment:
      POSTGRES_DB: falist
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: falist_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/falist
      SPRING_DATASOURCE_USERNAME: lucas
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
