version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: falist_frontend
    command: bash -c "bin/rails s -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      WEB_CONCURRENCY: 1
      API_URL: http://localhost:8080 # URL do teu back-end em Spring Boot
    volumes:
      - .:/rails
